### ISSUE TITLE
Web page crash crawling canal-u.tv

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#139]
See https://farm.openzim.org/pipeline/7f11d6889473fadf15947b26

The file should be bigger of course.

I suspect a Zimit configuration problem, but not obvious to me.

**Comment by rgaudin** [comment]
Here's what the log says:

```
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
Page Load Failed: https://www.canal-u.tv/, Reason: Error: Page crashed!
[DEBUG] Confirming output is writable using /output/tmp4x19oviq
[DEBUG] Title: cultureGnum
[DEBUG] Language: fra
[DEBUG] Favicon: https://www.canal-u.tv/themes/custom/canalu/favicon.ico
[INFO] Adding illustration from https://www.canal-u.tv/themes/custom/canalu/favicon.ico
[DEBUG] Found 15 records in WARCs
```

This is not zimit territory.

An upstream ticket could be created… browsertrix-crawler / pupeeter / chrome ?

**Comment by rgaudin** [comment]
Increased RAM and it's now running. That's second scenario of *weird crash* that gets fixed by increasing RAM. Newer crawler (newer chrome) might be more resource consuming.
