### ISSUE TITLE
zimit unable to find WARC records if run behind http proxy

### ISSUE THREAD

**Issue by memchr** [openzim/zimit#165]
If environment variable `PROXY_HOST` and `PROXY_PORT` is set, zimit will complain unable to find WARC records when creating ZIM file.

example:
```
$ docker run -v /output:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb \
        -e PROXY_HOST=172.17.0.1 -e PROXY_PORT=9001 \
        openzim/zimit zimit \
        --url https://ss64.com \
        --name ss64 \
        --workers 4 \
        --waitUntil domcontentloaded
```

output:
```
----------
Testing warc2zim args
Running: warc2zim --name ss64 --output /output --url https://ss64.com
[INFO] Arguments valid, no inputs to process. Exiting with error code 100

----------
Output to tempdir: /output/.tmp7zlpbjbl - will delete
Running browsertrix-crawler crawl: crawl --workers 4 --newContext page --waitUntil domcontentloaded --depth -1 --timeout 90 --exclude User_talk:|Talk:|User: --behaviors autoplay,autofetch,siteSpecific --behaviorTimeout 90 --url https://ss64.com --userAgentSuffix +Zimit  --cwd /output/.tmp7zlpbjbl
Storing state in memory
Text Extraction: Disabled10:12:43.654

== Start:     2023-01-01 10:12:43.654
== Now:       2023-01-01 10:13:45.391 (running for 1.0 minutes)
== Progress:  196 / 196 (100.00%), errors: 0 (0.00%)
== Remaining: 0.0 ms (@ 3.17 pages/second)
== Sys. load: 24.7% CPU / 60.1% memory
== Workers:   4
   #0 IDLE
   #1 IDLE
   #2 IDLE
   #3 IDLE
Saving crawl state to: /output/.tmp7zlpbjbl/collections/crawl-20230101101243200/crawls/crawl-20230101101345-23c6e7a54f67.yaml
Waiting to ensure pending data is written to WARCs...

----------
Processing 0 WARC files to ZIM
[ERROR] Unable to find WARC record for main page: https://ss64.com, ZIM not created

----------
Cleanup, removing temp dir: /output/.tmp7zlpbjbl
Traceback (most recent call last):
  File "/usr/bin/zimit", line 470, in <module>
    zimit()
  File "/usr/bin/zimit", line 390, in zimit
    return warc2zim(warc2zim_args)
  File "/usr/local/lib/python3.8/dist-packages/warc2zim/main.py", line 808, in warc2zim
    return warc2zim.run()
  File "/usr/local/lib/python3.8/dist-packages/warc2zim/main.py", line 378, in run
    self.find_main_page_metadata()
  File "/usr/local/lib/python3.8/dist-packages/warc2zim/main.py", line 504, in find_main_page_metadata
    raise KeyError(msg)
KeyError: 'Unable to find WARC record for main page: https://ss64.com, ZIM not created'
```

**Comment by rgaudin** [comment]
Yes, the [crawler](https://github.com/webrecorder/browsertrix-crawler) uses those internally to capture traffic as pywb serves traffic to chrome during crawling. You can't set those.

My understanding [from the README](https://github.com/webrecorder/browsertrix-crawler#configuring-chromium--puppeteer--pywb) is that `SOCKS_HOST`/`SOCKS_PORT` should allow an *upstream* proxy but I tested it and it doesn't work: no WARC record is created.

I suggest you open a ticket there (browsertrix) asking if it should be supported and how. I'm closing this one as not supported but I will reopen depending on the outcome of the new ticket.
