### ISSUE TITLE
Browsertrix crawler stops on page crashing

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#266]
We have multiple instances where a Browsertrix crawl ends-up with this kind of errors:

```
{"timestamp":"2024-01-15T08:17:30.893Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://solar.lowtechmagazine.com/pl/2020/04/fruit-trenches-cultivating-subtropical-plants-in-freezing-temperatures/","workerid":0}}
{"timestamp":"2024-01-15T08:17:30.991Z","logLevel":"warn","context":"general","message":"Link Extraction failed in frame","details":{"reason":{"name":"TargetCloseError"},"page":"https://solar.lowtechmagazine.com/pl/2020/01/how-sustainable-is-a-solar-powered-website/","workerid":0}}
{"timestamp":"2024-01-15T08:17:31.478Z","logLevel":"error","context":"worker","message":"Page Crashed","details":{"type":"exception","message":"Page crashed!","stack":"Error: Page crashed!\n    at #onTargetCrashed (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:284:28)\n    at file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:153:41\n    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:248\n    at Array.map (<anonymous>)\n    at Object.emit (file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:232)\n    at CDPSessionImpl.emit (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:82:22)\n    at CDPSessionImpl._onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:425:18)\n    at Connection.onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:255:25)\n    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/NodeWebSocketTransport.js:46:32)\n    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)","page":"https://solar.lowtechmagazine.com/pl/2020/04/fruit-trenches-cultivating-subtropical-plants-in-freezing-temperatures/","workerid":0}}
{"timestamp":"2024-01-15T08:17:31.479Z","logLevel":"info","context":"pageStatus","message":"Page Finished","details":{"loadState":2,"page":"https://solar.lowtechmagazine.com/pl/2020/04/fruit-trenches-cultivating-subtropical-plants-in-freezing-temperatures/","workerid":0}}

{"timestamp":"2024-01-15T08:17:31.701Z","logLevel":"error","context":"worker","message":"Page Crashed","details":{"type":"exception","message":"Page crashed!","stack":"Error: Page crashed!\n    at #onTargetCrashed (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:284:28)\n    at file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:153:41\n    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:248\n    at Array.map (<anonymous>)\n    at Object.emit (file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:232)\n    at CDPSessionImpl.emit (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:82:22)\n    at CDPSessionImpl._onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:425:18)\n    at Connection.onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:255:25)\n    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/NodeWebSocketTransport.js:46:32)\n    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)","page":"about:blank?_browsertrixkozykf79y5c","workerid":0}}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "crashed".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Let's track these occurences in this issue until we know what to report upstream (or not).

Last known occurrences: 
- [mesquartierschinois_fr](https://farm.openzim.org/recipes/mesquartierschinois_fr) on task https://farm.openzim.org/pipeline/787b96ee-36df-4d3d-96d5-758ca67b52df/debug with Browsertrix-Crawler 0.12.3 (with warcio.js 1.6.2 pywb 2.7.4) on worker athena18
- [solar.lowtechmagazine.com](https://farm.openzim.org/recipes/solar.lowtechmagazine.com) on task https://farm.openzim.org/pipeline/ebbea738-c84d-4b9c-a4a4-2476e03581a1/debug with Browsertrix-Crawler 0.12.3 (with warcio.js 1.6.2 pywb 2.7.4) on worker chance

**Comment by benoit74** [comment]
- [mesquartierschinois_fr](https://farm.openzim.org/recipes/mesquartierschinois_fr) again on task https://farm.openzim.org/pipeline/29998e1f-6ffc-423f-934f-911aa3eb7ec0 with Browsertrix-Crawler 0.12.4 (with warcio.js 1.6.2 pywb 2.7.4) on worker athena18

**Comment by benoit74** [comment]
- [solar.lowtechmagazine.com](https://farm.openzim.org/recipes/solar.lowtechmagazine.com) again on task https://farm.openzim.org/pipeline/6e4a0355-a69b-4849-98ab-ab1f0960aaf2/debug with Browsertrix-Crawler 0.12.4 (with warcio.js 1.6.2 pywb 2.7.4) on worker athena18

**Comment by benoit74** [comment]
- [solar.lowtechmagazine.com](https://farm.openzim.org/recipes/solar.lowtechmagazine.com) again on task https://farm.openzim.org/pipeline/ebf9d7d4-ab85-48bd-9363-a988694050ac with Browsertrix-Crawler 0.12.4 (with warcio.js 1.6.2 pywb 2.7.4) on worker athena18

Something important I did not noticed before: there are in fact many "Page Crashed" situations in the log (72 here) but the last one stops the crawl with an additional message we do not have for other page crash. Looks like the situation here is that it does not even achieves to initialize the page. It is important to note that between the 72 page crashes, some pages succeeded to be crawled.

```
{"timestamp":"2024-02-17T01:51:16.156Z","logLevel":"warn","context":"worker","message":"Error getting new page","details":{"workerid":0,"type":"exception","message":"timed out","stack":"Error: timed out\n    at PageWorker.initPage (file:///app/util/worker.js:135:17)\n    at async PageWorker.runLoop (file:///app/util/worker.js:254:22)\n    at async PageWorker.run (file:///app/util/worker.js:227:7)\n    at async Promise.allSettled (index 0)\n    at async Crawler.crawl (file:///app/crawler.js:887:5)\n    at async Crawler.run (file:///app/crawler.js:323:7)"}}
```

**Comment by benoit74** [comment]
See #283 for what looks like a new symptom of what has maybe the same underlying cause.

**Comment by benoit74** [comment]
I've reported the issue(s) upstream.

**Comment by benoit74** [comment]
- [ir.voanews.com_persian](https://farm.openzim.org/recipes/ir.voanews.com_persian) again on task https://farm.openzim.org/pipeline/4889a582-f24d-4364-acad-507c5d94ced6 with Browsertrix-Crawler 0.12.4 (with warcio.js 1.6.2 pywb 2.7.4) on worker athena18

**Comment by benoit74** [comment]
- [ndla.no_no_all](https://farm.openzim.org/recipes/ndla.no_no_all) on task https://farm.openzim.org/pipeline/1586bd19-22c2-4275-ae2e-abc266e6c7fe with Browsertrix-Crawler 0.12.4 (with warcio.js 1.6.2 pywb 2.7.4) on worker athena18

**Comment by benoit74** [comment]
Looks like Browsertrix-Crawler 1.x solved the issue, let's close this one
