### ISSUE TITLE
"bpf_prog_query(BPF_CGROUP_DEVICE) failed: function not implemented: unknown."

### ISSUE THREAD

**Issue by vitaly-zdanevich** [openzim/zimit#391]
```
$ docker run ghcr.io/openzim/zimit zimit --help
Unable to find image 'ghcr.io/openzim/zimit:latest' locally
latest: Pulling from openzim/zimit
31e907dcc94a: Pull complete 
11bc3572a5fb: Pull complete 
e257c698462b: Pull complete 
3f96df4a8a68: Pull complete 
46ae4a86e04b: Pull complete 
7a836a2afc2c: Pull complete 
b96c3516aa59: Pull complete 
a7829dc28c41: Pull complete 
8cc05d1d772a: Pull complete 
5e67f644181c: Pull complete 
1e47ec8e8fdf: Pull complete 
286bcab37f68: Pull complete 
be3a79827479: Pull complete 
8ccfe4e503b6: Pull complete 
f9aa511193f5: Pull complete 
87092ef46b8b: Pull complete 
12c6088a2b4a: Pull complete 
0cfd3ad01cc8: Pull complete 
c2c742e9b7f9: Pull complete 
7364a1fab386: Pull complete 
a78f10b69a0e: Pull complete 
29b68f4bc1a8: Pull complete 
8fdd99a75ff1: Pull complete 
060f8667745a: Pull complete 
4a322d7dbe48: Pull complete 
ba9910d5011b: Pull complete 
11a598bb87ab: Pull complete 
2551c9ad7a60: Pull complete 
75cc1fd313bd: Pull complete 
906042a43e98: Pull complete 
0e0bb393de26: Pull complete 
efc70c63fd14: Pull complete 
6575ef3d20c4: Pull complete 
1453168d44b8: Pull complete 
5e5156b6c37c: Pull complete 
Digest: sha256:3495432381ec733bb1d2b069d7dde2048fb1794ac36be68f2134e479094da462
Status: Downloaded newer image for ghcr.io/openzim/zimit:latest
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: bpf_prog_query(BPF_CGROUP_DEVICE) failed: function not implemented: unknown.
ERRO[0159] error waiting for container: context canceled 
```

I have a [custom Gentoo kernel](https://gitlab.com/vitaly-zdanevich-configs/linux-kernel-thinkpad-t430/-/blob/dc68fe82392e5e2022e6807c817947d3af775504/.config) (with a few disabled modules), maybe I need to enable something.

**Comment by vitaly-zdanevich** [comment]
In my kernel I enabled
CONFIG_BPF_SYSCALL
CONFIG_CGROUP_BPF

and now I have another error:

```
$ docker run ghcr.io/openzim/zimit zimit --help
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 688, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 372, in run
    zimit_args, warc2zim_args = parser.parse_known_args(raw_args)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1941, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 2162, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 2102, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.12/argparse.py", line 2017, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.12/argparse.py", line 1156, in __call__
    parser.print_help()
  File "/usr/lib/python3.12/argparse.py", line 2648, in print_help
    self._print_message(self.format_help(), file)
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 2632, in format_help
    return formatter.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 299, in format_help
    help = self._root_section.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 229, in format_help
    item_help = join([func(*args) for func, args in self.items])
                      ^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 229, in format_help
    item_help = join([func(*args) for func, args in self.items])
                      ^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 559, in _format_action
    help_text = self._expand_help(action)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 656, in _expand_help
    return self._get_help_string(action) % params
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
ValueError: unsupported format character ' ' (0x20) at index 99
```

**Comment by benoit74** [comment]
Regarding your first comment, this is obviously linked to your custom kernel and your docker installation, nothing we can really help with.

Regarding your second one, thank you help seems indeed broken, I've opened https://github.com/openzim/zimit/issues/393
