### ISSUE TITLE
Failed to start container: No closing quotation

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#404]
In this [zimit run](https://farm.zimit.kiwix.org/pipeline/3c4a7789-47f0-4341-997a-d103dc292993/debug), it looks like the worker failed to run the scraper container.
It's unclear why but it looks like a typo in the image definition.

@benoit74 does that ring a bell? 

```
Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
             ^^^^^^^^^^^^
  File "/usr/src/app/task/worker.py", line 735, in run
    self.start_scraper()
  File "/usr/src/app/task/worker.py", line 307, in start_scraper
    self.scraper = start_scraper(
                   ^^^^^^^^^^^^^^
  File "/usr/src/app/common/docker.py", line 425, in start_scraper
    return run_container(
           ^^^^^^^^^^^^^^
  File "/usr/src/app/common/docker.py", line 92, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/common/docker.py", line 50, in retried_docker_call
    return docker_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/models/containers.py", line 873, in run
    container = self.create(image=image, command=command,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/models/containers.py", line 932, in create
    resp = self.client.api.create_container(**create_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/api/container.py", line 431, in create_container
    config = self.create_container_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/api/container.py", line 442, in create_container_config
    return ContainerConfig(self._version, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/types/containers.py", line 708, in __init__
    command = split_command(command)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/utils/utils.py", line 478, in split_command
    return shlex.split(command)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/shlex.py", line 313, in split
    return list(lex)
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/shlex.py", line 300, in __next__
    token = self.get_token()
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/shlex.py", line 109, in get_token
    raw = self.read_token()
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

```

**Comment by benoit74** [comment]
Absolutely not ... interesting to keep open should it happen again in coming weeks.
