### ISSUE TITLE
Zimit crashes when trying to archive a specific website

### ISSUE THREAD

**Issue by adrian52999** [openzim/zimit#418]
Hello, 

So I tried to archive nutrition.org three times, and all three attempts ended in the same way:
I leave my PC overnight, and when I get to it, docker is closed(no icon on the taskbar) and it doesn't start up when I try to. I check taskmgr and it has some processes running (docker backend and one more I forgot). I kill the processes, and I can start docker up. Weird, right?

I open docker, go to the container log, and it appears that zimit has finished crawling but runs into an problem:

`2024-10-27 10:09:53 {"timestamp":"2024-10-27T08:09:53.171Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://www.nutritionvalue.org/food_brand_starts_with_Milc.html","workerid":9}}
2024-10-27 10:09:53 {"timestamp":"2024-10-27T08:09:53.309Z","logLevel":"info","context":"behavior","message":"Run Script Finished","details":{"frameUrl":"https://www.nutritionvalue.org/foods_by_MILKADAMIA_brand.html","page":"https://www.nutritionvalue.org/foods_by_MILKADAMIA_brand.html","workerid":3}}
2024-10-27 10:09:53 {"timestamp":"2024-10-27T08:09:53.309Z","logLevel":"info","context":"behavior","message":"Behaviors finished","details":{"finished":1,"page":"https://www.nutritionvalue.org/foods_by_MILKADAMIA_brand.html","workerid":3}}
2024-10-27 10:09:53 [zimit::2024-10-27 08:09:53,463] INFO:
2024-10-27 10:09:53 [zimit::2024-10-27 08:09:53,463] INFO:----------
2024-10-27 10:09:53 [zimit::2024-10-27 08:09:53,463] INFO:Cleanup, removing temp dir: /output/.tmptu31bfln
2024-10-27 10:09:53 node:events:497
2024-10-27 10:09:53       throw er; // Unhandled 'error' event
2024-10-27 10:09:53       ^
2024-10-27 10:09:53 
2024-10-27 10:09:53 Error: EIO: i/o error, write
2024-10-27 10:09:53 Emitted 'error' event on WriteStream instance at:
2024-10-27 10:09:53     at emitErrorNT (node:internal/streams/destroy:169:8)
2024-10-27 10:09:53     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-10-27 10:09:53     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-10-27 10:09:53   errno: -5,
2024-10-27 10:09:53   code: 'EIO',
2024-10-27 10:09:53   syscall: 'write'
2024-10-27 10:09:53 }
2024-10-27 10:09:53 
2024-10-27 10:09:53 Node.js v20.17.0
2024-10-27 10:09:53 Traceback (most recent call last):
2024-10-27 10:09:53   File "/usr/bin/zimit", line 8, in <module>
2024-10-27 10:09:53     sys.exit(zimit.zimit())
2024-10-27 10:09:53              ^^^^^^^^^^^^^
2024-10-27 10:09:53   File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 688, in zimit
2024-10-27 10:09:53     run(sys.argv[1:])
2024-10-27 10:09:53   File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 574, in run
2024-10-27 10:09:53     raise subprocess.CalledProcessError(crawl.returncode, cmd_args)
2024-10-27 10:09:53 subprocess.CalledProcessError: Command '['crawl', '--failOnFailedSeed', '--workers', '10', '--waitUntil', 'load', '--depth', '-1', '--timeout', '90', '--behaviors', 'autoplay,autofetch,siteSpecific', '--behaviorTimeout', '90', '--diskUtilization', '90', '--url', 'https://www.nutritionvalue.org/', '--userAgentSuffix', '+Zimit', '--mobileDevice', 'Pixel 2', '--cwd', '/output/.tmptu31bfln']' returned non-zero exit status 1.`

Now that I am looking at it, it appears that this error is due to me killing the process, though it is extremely weird why docker disappears and acts as if it is closed. There were no signs of Docker running, other than the backend process and the fact I couldn't open it.

Something worth adding - I opened the last 100 lines of the log (not the docker log but the actual log, which was almost 4GB) in Powershell, and there was no error message. It was just the crawl info messages. Could it be that something is causing Docker to enter this close to exited state that keeps the script on life support, without actually running?

Anyone run into this?

**Comment by adrian52999** [comment]
Something more to add, this is the output of one second time this happened:

2024-10-23 12:58:25 {"timestamp":"2024-10-23T09:58:25.120Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://www.nutritionvalue.org/nutritioncalculator.php?action=add&ids=866410","workerid":5}}
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,139] INFO:
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,140] INFO:
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,140] INFO:SIGINT/SIGTERM received, stopping zimit
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,140] INFO:
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,140] INFO:
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,858] INFO:
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,858] INFO:----------
2024-10-23 12:58:25 [zimit::2024-10-23 09:58:25,858] INFO:Cleanup, removing temp dir: /output/.tmp57ad8i5d

There was no .zim file in the directory.

**Comment by benoit74** [comment]
Everything you're describing indicates that zimit was working fine:
- crawler was still downloading pages
- process was still listed in the running processes
- when you stopped it, it stopped as required, including final cleanup

The fact that the icon was gone is Docker issue, nothing we can help with, especially since there is a significant chance this is linked to your local setup.

Closing this as from my PoV we have nothing to do, but do not hesitate to ask to reopen should you have more evidence that there is a real problem with zimit container.
