### ISSUE TITLE
Zimit seems to not always scrape the main page properly

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#83]
... and process crashes with:
```
[DEBUG] Confirming output is writable using /output/tmpi9rb0ndm
[ERROR] Unable to find WARC record for main page: http://corpse.jp/bd/?cont=5#sp01, ZIM not created
Traceback (most recent call last):
  File "/usr/bin/zimit", line 333, in <module>
    zimit()
  File "/usr/bin/zimit", line 265, in zimit
    return warc2zim(warc2zim_args)
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 768, in warc2zim
    return warc2zim.run()
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 402, in run
    self.find_main_page_metadata()
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 532, in find_main_page_metadata
    raise KeyError(msg)
KeyError: 'Unable to find WARC record for main page: http://corpse.jp/bd/?cont=5#sp01, ZIM not created'
```
See:
https://farm.youzim.it/pipeline/c9516031a7d2fa9c7c988006/debug

**Comment by kelson42** [comment]
Other cases:
* https://farm.youzim.it/pipeline/ebcb87c4920ec74374e7bff5/debug

**Comment by rgaudin** [comment]
Fixed in https://github.com/openzim/warc2zim/commit/9eec367b59fc8351d5233bbddf664e2cd8ca97ac
